[general]
import = [
    "~/.config/alacritty/tokyo_night.toml"
]

[window]

decorations = "Full"
decorations_theme_variant = "Dark"

[font]
# normal = { family = "Hurmit Nerd Font", style = "Regular" }
# bold = { family = "Hurmit Nerd Font", style = "Bold" }
# italic = { family = "Hurmit Nerd Font", style = "Italic" }
# bold_italic = { family = "Hurmit Nerd Font", style = "Bold Italic" }

normal = { family = "Mononoki Nerd Font Mono", style = "Regular" }
bold = { family = "Mononoki Nerd Font Mono", style = "Bold" }
italic = { family = "Mononoki Nerd Font Mono", style = "Italic" }
bold_italic = { family = "Mononoki Nerd Font Mono", style = "Bold Italic" }
size = 20

[cursor]
style = { shape = "Block", blinking = "On" } 

[mouse]
hide_when_typing = true

